name: IK-1G-OpenClash-PassWall

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y build-essential cmake git libncurses5-dev python3

      - name: Clone ImmortalWrt 23.05
        run: |
          git clone -b openwrt-23.05 --single-branch --depth=1 https://github.com/immortalwrt/immortalwrt
          cd immortalwrt

      - name: Add OpenClash & PassWall feeds
        run: |
          cd immortalwrt
          echo "src-git openclash https://github.com/vernesong/OpenClash.git;dev" >> feeds.conf.default
          echo "src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall-packages.git;main" >> feeds.conf.default
          echo "src-git passwall https://github.com/xiaorouji/openwrt-passwall.git;main" >> feeds.conf.default

      - name: Update & Install feeds
        run: |
          cd immortalwrt
          ./scripts/feeds update -a || true
          ./scripts/feeds install -a || true

      - name: 1GB内存精简配置 + OpenClash + PassWall
        run: |
          cd immortalwrt
          cat > .config << EOF
            CONFIG_TARGET_x86=y
            CONFIG_TARGET_x86_64=y
            CONFIG_TARGET_x86_64_DEVICE_generic=y
            CONFIG_TARGET_ROOTFS_PARTSIZE=1024
            CONFIG_PACKAGE_luci=y
            CONFIG_PACKAGE_luci-theme-bootstrap=y
            CONFIG_PACKAGE_luci-app-openclash=y
            CONFIG_PACKAGE_luci-app-passwall=y
            CONFIG_SIGNED_PACKAGES=n
            CONFIG_KERNEL_DEBUG_INFO=n
            CONFIG_KERNEL_PROFILING=n
            CONFIG_VMDK_IMAGES=y
            CONFIG_QCOW2_IMAGES=y
            CONFIG_ISO_IMAGES=y
          EOF
          make defconfig

      - name: Download Libraries
        run: |
          cd immortalwrt
          make download -j$(nproc) V=s

      - name: Build
        run: |
          cd immortalwrt
          make -j1 V=s

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-x86-1g-openclash-passwall
          path: immortalwrt/bin/targets/x86/*/*

